name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20 # Replace with the desired Go version

      - name: Build
        
        run: go build -o app ./backend/cmd/main.go

      - name: Run tests
        run: go test ./backend...

  # deploy:
  #   name: Deploy
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #     - name: Deploy to Server
  #       run: |
  #         # Add your deployment commands here
