# Stage 1: Build the React application
FROM node:20.5.0 AS build

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json before other files
# Utilize Docker cache to save re-installing dependencies if unchanged
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy all files
COPY . .

# Build application
RUN npm run build

RUN npm prune --production

EXPOSE 3000

CMD ["npm", "start"]

