FROM node:20.5.0-alpine AS base

RUN apk update && apk --no-cache --virtual build-dependencies add python3 make g++
WORKDIR /usr/src/app

COPY package*.json ./

RUN npm clean-install

COPY . .

RUN npm run build

FROM caddy:2.6.4-alpine

COPY Caddyfile /etc/caddy/Caddyfile
COPY --from=base /usr/src/app/build/ /srv

