version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - '5000:5000'
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=cash-manager
      - JWT_SECRET=a8f5f167f44f4964e6c998dee827110c
      - JWT_EXPIRATION=3600
      - CORS_ORIGIN=http://localhost:3000
    depends_on:
     - db
  db:
    image: postgres:16beta2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cash-manager
    ports:
      - '5432:5432'
  caddy:
    image: caddy:2.6.4-alpine
    ports:
      - '80:80'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
