version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - '80:80'
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - '5000:5000'
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=database
      - JWT_SECRET=a8f5f167f44f4964e6c998dee827110c
      - JWT_EXPIRATION=3600
      - NODE_ENV=development
      - PORT=3000
      - CORS_ORIGIN=http://localhost:3000
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=database
    ports:
      - '5432:5432'
  caddy:
    image: caddy:builder-alpine
    ports:
      - '80:80'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
