FROM denoland/deno:alpine-1.35.1

# Set the Working Directory
WORKDIR /app

# Copy the Project Files to Docker
COPY ./src .

# Expose the port number that your app runs on
EXPOSE 5000

# Run your Program
CMD ["run", "--allow-net", "--allow-read", "--allow-env", "server.ts"]
