# Use the official Golang image
FROM golang:1.21rc3

# Set the working directory
WORKDIR /app/backend

# Copy the necessary files
COPY . /app/backend

# Build the backend binary
RUN go build -o backend ./cmd/main.go

# Expose the port
EXPOSE 5000

# Run the backend server
CMD ["./backend"]
