# Use the official Golang image
FROM golang:latest

# Set the working directory
WORKDIR /app/backend

# Copy the necessary files
COPY ./backend /app/backend

# Build the backend binary
RUN go build -o backend .

# Expose the port
EXPOSE 5000

# Run the backend server
CMD ["./backend"]
