kind: pipeline
name: default

workspace:
  base: /app

steps:
  - name: clone
    image: alpine/git
    commands:
      - git clone https://github.com/leonardopoggiani/cash-manager-2.0.git /app

  - name: build-backend
    image: golang:latest
    commands:
      - cd /app/backend
      - go build . -o backend

  - name: test-backend
    image: golang:latest
    commands:
      - cd /app/backend
      - go test ./...

  - name: build-frontend
    image: node:latest
    commands:
      - cd /app/frontend
      - npm install
      - npm run build

trigger:
  event:
    - push
  branch:
    - main
